### ISSUE TITLE
如何利用任务计划程序自动运行？

### ISSUE THREAD

**Issue by cxw620** [CrazyBoyFeng/huaweicloud-optimize-dns-cloudflare-ip#1]
现在得手动点击按键退出，如何修改代码在完成即便出现错误时也自动退出？
请大佬指教！

**Comment by CrazyBoyFeng** [comment]
执行 cmd 文件或 bash 文件的时候，添加一个 start 参数即可。
![image](https://user-images.githubusercontent.com/1733254/109388163-52dcc500-7940-11eb-8321-fe06cf0ade2f.png)

**Comment by CrazyBoyFeng** [comment]
我修改了一下，添加了几个参数以控制退出方式，以及隐藏窗口运行模式。

任务计划设置操作时，可以带上参数。
