### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by yebingo** [CrazyBoyFeng/huaweicloud-optimize-dns-cloudflare-ip#3]
![image](https://user-images.githubusercontent.com/26788533/115702737-dd1f3380-a39b-11eb-9a9d-077056f836b2.png)
执行脚本报错，如上图所示，可以帮忙看下是什么原因吗？

**Comment by CrazyBoyFeng** [comment]
操作系统是什么？使用的是什么sh？是DNSPod对吧？

另外这个 `cloudflare.sh` 似乎是修改过的，行号跟我的脚本对不上。  
`invalid cidr address` 好像既不是我的脚本，也不是 `CloudflareST` 的输出。

**Comment by yebingo** [comment]
> 操作系统是什么？使用的是什么sh？是DNSPod对吧？
> 
> 另外这个 `cloudflare.sh` 似乎是修改过的，行号跟我的脚本对不上。
> `invalid cidr address` 好像既不是我的脚本，也不是 `CloudflareST` 的输出。

我用的是centos7系统，是DNSPod
因为前面报错，我把几个function位置提前了，并把 /CloudflareST.exe 改成了/CloudflareST，然后保存为cloudflare.sh文件。

**Comment by CrazyBoyFeng** [comment]
试一下刚刚修改的：  
https://github.com/CrazyBoyFeng/Optimize-DnsCloudflareIP/blob/95eb2f7bcb84906d314cae983b0aed3cd4e5d71f/DNSPod/optimize-dns-cloudflare-ip.bash

**Comment by yebingo** [comment]
> 试一下刚刚修改的：
> https://github.com/CrazyBoyFeng/Optimize-DnsCloudflareIP/blob/95eb2f7bcb84906d314cae983b0aed3cd4e5d71f/DNSPod/optimize-dns-cloudflare-ip.bash

试了下，报了”未知的名称或服务“的错误

**Comment by CrazyBoyFeng** [comment]
第几行？能把完整的提示粘一下吗？隐藏掉你的域名即可。

**Comment by yebingo** [comment]
> 第几行？能把完整的提示粘一下吗？隐藏掉你的域名即可。

如下图所示：
![image](https://user-images.githubusercontent.com/26788533/115752910-263bab80-a3cd-11eb-9b2f-084eb97c5223.png)

**Comment by CrazyBoyFeng** [comment]
49 行和 80 行我少打了个分隔符，已添加。

另外你用的 `CloudflareST 1.4.7` 老版本不兼容 `-sl 0.1` 小数，你可以把 31 行的 `-sl 0.1` 删掉。

再试试吧：https://github.com/CrazyBoyFeng/Optimize-DnsCloudflareIP/blob/25349365bbf986433d0d3ea93c11af9d827428ef/DNSPod/optimize-dns-cloudflare-ip.bash

**Comment by CrazyBoyFeng** [comment]
49 行我也少打了个，换这个 2534 开头的的更新试试，上面的链接我改了。

**Comment by yebingo** [comment]
> 49 行和 80 行我少打了个分隔符，已添加。
> 
> 另外你用的 `CloudflareST 1.4.7` 老版本不兼容 `-sl 0.1` 小数，你可以把 31 行的 `-sl 0.1` 删掉。
> 
> 再试试吧：https://github.com/CrazyBoyFeng/Optimize-DnsCloudflareIP/blob/25349365bbf986433d0d3ea93c11af9d827428ef/DNSPod/optimize-dns-cloudflare-ip.bash

试了下，报了如下问题：
![image](https://user-images.githubusercontent.com/26788533/115805164-fe713580-a416-11eb-83bf-be6d1c04543f.png)

**Comment by yebingo** [comment]
> 49 行和 80 行我少打了个分隔符，已添加。
> 
> 另外你用的 `CloudflareST 1.4.7` 老版本不兼容 `-sl 0.1` 小数，你可以把 31 行的 `-sl 0.1` 删掉。
> 
> 再试试吧：https://github.com/CrazyBoyFeng/Optimize-DnsCloudflareIP/blob/25349365bbf986433d0d3ea93c11af9d827428ef/DNSPod/optimize-dns-cloudflare-ip.bash

刚改了下 又报了这样的错误：
![image](https://user-images.githubusercontent.com/26788533/115832203-355e4000-a445-11eb-96ce-a133c440308f.png)

**Comment by CrazyBoyFeng** [comment]
期待一元表达式是因为 IP 有两行数据，现在改成只选第一个了。

> No valid records  

这个提示是因为没在 DNSPod 服务器上找到与此 IP 对应的记录。请先看一下你的控制台，确保有设定为此 IP 的 A 记录。

**Comment by yebingo** [comment]
> 期待一元表达式是因为 IP 有两行数据，现在改成只选第一个了。
> 
> > No valid records
> 
> 这个提示是因为没在 DNSPod 服务器上找到与此 IP 对应的记录。请先看一下你的控制台，确保有设定为此 IP 的 A 记录。

![image](https://user-images.githubusercontent.com/26788533/115833432-a2bea080-a446-11eb-8e2e-d42db5fefd25.png)
DNSpod 上是有这条A记录的

**Comment by CrazyBoyFeng** [comment]
那么在 52 行之后，53 行之前，添加一行：`echo "$response"`，看看服务器返回的提示是什么。

**Comment by yebingo** [comment]
> 那么在 52 行之后，53 行之前，添加一行：`echo "$response"`，看看服务器返回的提示是什么。

返回的是code为1，message为”操作已成功完成“

**Comment by CrazyBoyFeng** [comment]
返回的信息包含你的域名和记录吗？有`records`字段吗？

你可以把账户、域名、子域名、id、时间隐藏后粘贴上来。
