### ISSUE TITLE
能不能增加同时更改同zone id下多个子域名的ip的功能？

### ISSUE THREAD

**Issue by cxw620** [CrazyBoyFeng/huaweicloud-optimize-dns-cloudflare-ip#4]
如题。
大概就是输入了几个域名就改几个
👇
Param([switch]$ExitEnd,[switch]$ExitError)
#请先去华为云解析后台增加一条A记录或AAAA记录。
$domain = "xxx1.xxx.com";"xxx2.xxx.com"
$zone_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

**Comment by CrazyBoyFeng** [comment]
* 多个域名如果指向同一个 ip，建议 `xxx2` 通过 `cname` 指向 `xxx1`，脚本只更新 `xxx1`。
* 多个域名如果指向不同的 ip，建议开两个脚本，分别更新 `xxx1` 和 `xxx2`。两个脚本可以用不同的名字共存于同一个文件夹，在 windows 下它们需要各自的 `cmd` 启动器，只需要保持启动器文件名和脚本名一致即可。
